

services:
  postgres:
    image: postgres:15-alpine
    container_name: betteruptime-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: betteruptime
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - betteruptime-network

  # Optional: PgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: betteruptime-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@betteruptime.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - betteruptime-network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  betteruptime-network:
    driver: bridge
